version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fluent_futures_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: fluent_futures_wp
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  wpcli:
    image: wordpress:cli
    container_name: fluent_futures_cli
    user: "33:33" # Ejecutar como www-data para evitar problemas de permisos de archivos
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      MARIADB_TLS_DISABLE_PEER_VERIFICATION: "1"
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./mysql-client.cnf:/etc/my.cnf.d/client.cnf:ro
    depends_on:
      - db

volumes:
  db_data:
  wordpress_data:
